### PR TITLE
Merging Fixes From Various Forks

### PR DESCRIPTION
**Pull request by dwbapst**
I decided to take all the changes that have accrued across different forks for this plugin and try to unify them. I have been using this with Gedit for the past two months now and it seems pretty stable on my end, so here's a PR so you are aware.

### CODE REVIEW

**Comment by raelgc** [comment]
Thank you for the PR. I'll just run a quick test on it, then merge it.

**Comment by raelgc** [comment]
@dwbapst I just tested the version I had and this PR. None appears to works on Ubuntu 20.04 (Gnome 3.36).

**Comment by dwbapst** [comment]
Hi @raelgc,

Apologies for not responding for so long -- the pandemic has had me busy teaching and doing childcare, not much time to work on side projects.

Hmm. I'm on Mint, which was on Bionic until two week ago, and I haven't updated to Ubuntu Focal yet. Have you been able to get it working since you last checked my PR? I see there are conflicts now on the branch...

I have noticed one issue since we last spoke, which was that tabs aren't restored if the document title had spaces in it. Not sure if that's a new bug or what.

**Comment by raelgc** [comment]
Hi @dwbapst!

I got `master` working on 20.04 with commit d1328c30c018e761ed20532b37e9afbc193fd27c.

**Comment by dwbapst** [comment]
I've dealt with all the conflicts, I think, but I'm going to close this and make a new PR from a branch where the README says your repo, not mine...

**Pull request closed without merging**
