### PR TITLE
Create plugins dir if not existing

### PR DESCRIPTION
**Pull request by nsoranzo**

### CODE REVIEW

**Comment by raelgc** [comment]
Thank you @nsoranzo!

Just out of curiosity, which distro are you using?

**Comment by nsoranzo** [comment]
Thanks for merging so fast!
I'm on Ubuntu 14.04.2 LTS.

**Comment by raelgc** [comment]
Me too. Just wondering if I should create a package for this plugin.

**Comment by nsoranzo** [comment]
What about trying to push it to https://git.gnome.org/browse/gedit/tree/plugins ?

**Pull request merged**
