### PR TITLE
Merge changes from previous 

### PR DESCRIPTION
**Pull request by dwbapst**
This unifies recent changes and a number of changes on disparate forks of raelgc's fork of miccah's original restore-tabs.

### CODE REVIEW

**Comment by dwbapst** [comment]
In particular, this merged PR includes code to fix issues #15 and #18 from @hildogjr.

This PR also includes code from @Kasual.

**Comment by raelgc** [comment]
Thanks again, @dwbapst. I'll test this until the weekend and merge.

**Comment by dwbapst** [comment]
FYI - possible issue.

I've noticed that tabs containing files with spaces in their filenames aren't restored. Not sure if this is a regression or what, as apparently it took a long time for me to even notice this -- I also haven't tested yet to see if spaces in directories cause issues as well. Do you have this issue on your side, @raelgc ? 

Also, do you think you could open an issues tab for this repository, as @quixoitic's master is long dormant?

**Comment by raelgc** [comment]
I still didn't merge this PR because I still didn't have time to test it.

And I'm a bit afraid to merge, because basically I've been using the `@quixoitic` basic idea, just updating it to keep it working.

I tested `master` with a folder and document containing spaces in name and it worked.

About issues: I just enabled the issues tab.

**Comment by Wiggyboy** [comment]
This seems to work great for me, thanks!

**Comment by raelgc** [comment]
@Wiggyboy which distro and version?

**Comment by Wiggyboy** [comment]
@raelgc I run Ubuntu 20.04, gedit 3.36.2

**Pull request merged**
